"""
Django settings for replica_api project.

Generated by 'django-admin startproject' using Django 3.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
from .base import *

# SECURITY WARNING: keep the secret key used in production secret!
# noinspection SpellCheckingInspection
SECRET_KEY = 'pA#5oR>yqOve9YtK|^i%HgU$uMa\\I?a|G){@iR+D/S)X]fO1m{W(_5cU.PXjZ&e9B^9A~B&lhA.I+B<8'

# noinspection SpellCheckingInspection
JWT_SECRET_ENCRYPTION_KEY = 'ImQSFbAja9yVhOlp8W9Zy6cTW5naUhpwaPb5dL0ZBuI='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Logging
LOGGING['loggers']['']['handlers'].append('console')
LOGGING['loggers']['']['level'] = 'DEBUG'
