"""
Django settings for replica_api project.

Generated by 'django-admin startproject' using Django 3.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
# noinspection PyUnresolvedReferences
from .base import *

# SECURITY WARNING: keep the secret key used in production secret!
# noinspection SpellCheckingInspection
SECRET_KEY = '=.nF-OnqU?m[hZ=IY}3$I1Xm#Ke9)<wqefLUtAUfj0y|nO{XS-.`6?Aal]sVE3Q)|$O5t]$quVD#whCC'

JWT_SECRET_ENCRYPTION_KEY = 'HT4ZsxX92qE1n5kZdHd5iFZ3nNm_ASmQO6ktT8kaLkM='
