"""
Django settings for replica_api project.

Generated by 'django-admin startproject' using Django 3.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
# noinspection PyUnresolvedReferences
from .base import *

# SECURITY WARNING: keep the secret key used in production secret!
# noinspection SpellCheckingInspection
SECRET_KEY = 's.y$PflIx%.JYQ9epbn[G5Mb|VX2aH\\QD,^i\\Gy@u)XM!2e0PyQ9g`lN0<!TyAQr5m_.{lZ\\!Ni~p?-]'

# noinspection SpellCheckingInspection
JWT_SECRET_ENCRYPTION_KEY = '3I6s5gDG3eFAgN09iSVj973WzU5xL9x95Nz8EVVDKig='
