"""
Django settings for replica_api project.

Generated by 'django-admin startproject' using Django 3.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
# noinspection PyUnresolvedReferences
from .base import *

# SECURITY WARNING: keep the secret key used in production secret!
# noinspection SpellCheckingInspection
SECRET_KEY = '<-?^xA(`o}BW$3jO\\Bss1KA{(4B_!8<8=yx#R>w1ff?a*S}pZ<Iiu]UfsNsgL*/]G.3HSfECl[i\\]?8E'

# noinspection SpellCheckingInspection
JWT_SECRET_ENCRYPTION_KEY = 'OKYLF2oC4VhgwYg3JFhtzf1o7qJLATwYCTtoTdHlFaE='
